server {
    listen 80;
    server_name mail.rouzbehsayadifar.nl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mail.rouzbehsayadifar.nl;

    ssl_certificate     /www/server/panel/vhost/cert/mail.rouzbehsayadifar.nl/fullchain.pem;
    ssl_certificate_key /www/server/panel/vhost/cert/mail.rouzbehsayadifar.nl/privkey.pem;

    allow 10.70.0.0/24;
    allow 10.77.1.0/24;
    deny  all;

    location / {
        proxy_pass         http://127.0.0.1:3010;
        proxy_http_version 1.1;

        proxy_set_header Upgrade    $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
